/**
 * Created by mohadib on 1/30/17.
 */
export const CredentialActions = Object.freeze({
    SAVE_REQUEST: 'CREDENTIAL_SAVE_REQUEST',
    UPDATE_REQUEST: 'CREDENTIAL_UPDATE_REQUEST',
    SAVE_SUCCESS: 'CREDENTIAL_SAVE_SUCCESS',
    SAVE_ERROR: 'CREDENTIAL_SAVE_ERROR',
    CREATE_NEW: 'CREDENTIAL_CREATE_NEW',
    PROPERTY_UPDATED: 'CREDENTIAL_PROPERTY_UPDATED',
    RESET_ALERTS: 'CREDENTIAL_RESET_ALERTS',
    GET_LIST_REQUEST: 'CREDENTIAL_GET_ALL_REQUEST',
    GET_LIST_SUCCESS: 'CREDENTIAL_GET_ALL_SUCCESS',
    GET_LIST_ERROR: 'CREDENTIAL_GET_ALL_ERROR',
});
