/**
 * Created by mohadib on 1/30/17.
 */
export const CredentialActions = Object.freeze({
   SAVE_REQUEST: 'CREDENTIAL_SAVE_REQUEST',
   SAVE_SUCCESS: 'CREDENTIAL_SAVE_SUCCESS',
   SAVE_ERROR: 'CREDENTIAL_SAVE_ERROR',
   CREATE_NEW: 'CREDENTIAL_CREATE_NEW',
   PROPERTY_UPDATED: 'CREDENTIAL_PROPERTY_UPDATED'
});
