/**
 * Created by mohadib on 1/30/17.
 */
export const CredentialActions = Object.freeze({
   SAVE_REQUEST: 'CREDENTIAL_SAVE_REQUEST',
   UPDATE_REQUEST: 'CREDENTIAL_UPDATE_REQUEST',
   SAVE_SUCCESS: 'CREDENTIAL_SAVE_SUCCESS',
   SAVE_ERROR: 'CREDENTIAL_SAVE_ERROR',
   CREATE_NEW: 'CREDENTIAL_CREATE_NEW',
   PROPERTY_UPDATED: 'CREDENTIAL_PROPERTY_UPDATED',
   RESET_ALERTS: 'CREDENTIAL_RESET_ALERTS',
   CLEAR_ALL: 'CREDENTIAL_CLEAR_ALL',
   GET_LIST_REQUEST: 'CREDENTIAL_GET_ALL_REQUEST',
   GET_LIST_SUCCESS: 'CREDENTIAL_GET_ALL_SUCCESS',
   GET_LIST_ERROR: 'CREDENTIAL_GET_ALL_ERROR',
   GET_ONE_REQUEST: 'CREDENTIAL_GET_ONE_REQUEST',
   GET_ONE_SUCCESS: 'CREDENTIAL_GET_ONE_SUCCESS',
   GET_ONE_ERROR: 'CREDENTIAL_GET_ONE_ERROR',
   DELETE_REQUEST: 'CREDENTIAL_DELETE_REQUEST',
   DELETE_SUCCESS: 'CREDENTIAL_DELETE_SUCCESS',
   DELETE_ERROR: 'CREDENTIAL_DELETE_ERROR',
});

export const ProjectActions = Object.freeze({
   SAVE_REQUEST: 'PROJECT_SAVE_REQUEST',
   UPDATE_REQUEST: 'PROJECT_UPDATE_REQUEST',
   SAVE_SUCCESS: 'PROJECT_SAVE_SUCCESS',
   SAVE_ERROR: 'PROJECT_SAVE_ERROR',
   CREATE_NEW: 'PROJECT_CREATE_NEW',
   PROPERTY_UPDATED: 'PROJECT_PROPERTY_UPDATED',
   RESET_ALERTS: 'PROJECT_RESET_ALERTS',
   CLEAR_ALL: 'PROJECT_CLEAR_ALL',
   GET_LIST_REQUEST: 'PROJECT_GET_ALL_REQUEST',
   GET_LIST_SUCCESS: 'PROJECT_GET_ALL_SUCCESS',
   GET_LIST_ERROR: 'PROJECT_GET_ALL_ERROR',
   GET_ONE_REQUEST: 'PROJECT_GET_ONE_REQUEST',
   GET_ONE_SUCCESS: 'PROJECT_GET_ONE_SUCCESS',
   GET_ONE_ERROR: 'PROJECT_GET_ONE_ERROR',
   DELETE_REQUEST: 'PROJECT_DELETE_REQUEST',
   DELETE_SUCCESS: 'PROJECT_DELETE_SUCCESS',
   DELETE_ERROR: 'PROJECT_DELETE_ERROR',
});

export const ProjectGroupActions = Object.freeze({
   SAVE_REQUEST: 'PROJECT_GROUP_SAVE_REQUEST',
   UPDATE_REQUEST: 'PROJECT_GROUP_UPDATE_REQUEST',
   SAVE_SUCCESS: 'PROJECT_GROUP_SAVE_SUCCESS',
   SAVE_ERROR: 'PROJECT_GROUP_SAVE_ERROR',
   CREATE_NEW: 'PROJECT_GROUP_CREATE_NEW',
   PROPERTY_UPDATED: 'PROJECT_GROUP_PROPERTY_UPDATED',
   RESET_ALERTS: 'PROJECT_GROUP_RESET_ALERTS',
   CLEAR_ALL: 'PROJECT_GROUP_CLEAR_ALL',
   GET_LIST_REQUEST: 'PROJECT_GROUP_GET_ALL_REQUEST',
   GET_LIST_SUCCESS: 'PROJECT_GROUP_GET_ALL_SUCCESS',
   GET_LIST_ERROR: 'PROJECT_GROUP_GET_ALL_ERROR',
   GET_ONE_REQUEST: 'PROJECT_GROUP_GET_ONE_REQUEST',
   GET_ONE_SUCCESS: 'PROJECT_GROUP_GET_ONE_SUCCESS',
   GET_ONE_ERROR: 'PROJECT_GROUP_GET_ONE_ERROR',
   DELETE_REQUEST: 'PROJECT_GROUP_DELETE_REQUEST',
   DELETE_SUCCESS: 'PROJECT_GROUP_DELETE_SUCCESS',
   DELETE_ERROR: 'PROJECT_GROUP_DELETE_ERROR',
});

export const DisplayedGroup = Object.freeze({
   GROUP_SELECTED: 'GROUP_SELECTED'
});

export const AlertActions = Object.freeze({
   NEW_ALERT: 'NEW_ALERT',
   CLEAR_ALERTS: 'CLEAR_ALERTS',
   CLEAR_ALERT: 'CLEAR_ALERT'
});
